export {
  approveHubSpotWriteback,
  getHubSpotWritebackReview,
  listDecidedHubSpotWritebacks,
  listPendingHubSpotWritebacks,
  recordProposedHubSpotWriteback,
  rejectHubSpotWriteback,
  updateReviewDeskFeedbackNote,
  type ApproveHubSpotWritebackResult,
  type HubSpotWritebackPlanFieldUpdateView,
  type HubSpotWritebackReviewDetail,
  type HubSpotWritebackReviewItem,
  type HubSpotWritebackReviewState,
  type RecordProposedHubSpotWritebackInput,
} from "./internal/operations";
